#!/bin/bash 

keyword(){
  init
  keyword="$@"
  echo "$keyword" >> /tmp/keyword
  catfile "$keyword" && return 0
  runcmd "$keyword" 
  [[ "$keyword" =~ "snippet" ]] && find ~/.vim/snippets && return 0
  find ~/.vim/snippets -name "*$keyword*" 
}

catfile(){
  [[ ! -f "$1" ]] && return 1
  [[ -f "$1" ]] && [[ ! "$1" =~ ".filter" ]] && cat "$1" | filtertext && return 0
  [[ -f "$1" ]] && [[ "$1" =~ ".filter" ]] && source "$1" # echo "$VIMBUFFER" | sed 's/foo/bar/g'
}

runcmd(){
  cmd="$1"; iscommand=0; forbidden="rm sudo su" ; application=""
  for token in $cmd; do which "$token" &>/dev/null && iscommand=1; break; done # check if first arg is command 
  for token in $cmd; do 
    for sin in $forbidden; do [[ "$token" =~ "$sin " ]] && return 0; done 
  done 
  (( $iscommand == 1 )) && ${cmd} && return 0 || return 0 # seems fine, lets do it
  return 1
}

filtertext(){
  source ~/.bashizzle
  cat - | while read line; do 
    for k in "${!filter[@]}"; do # process variables from config
      strlen=${#k}
      [[ "${k:0:1}" == '$' ]] && eval "${k:1:strlen}='${filter[$k]}'"
      [[ ! "${k:0:1}" == '$' ]] && line=${line//$k/${filter[$k]}}
    done
    line="$(eval "echo \"$( echo "$line" | sed 's/"/\\"/g')\"")"; # process bash in snippet
    echo "$line"
  done
  return 0
}

init(){
  tpl="declare -A filter\nfilter['"'$'"AUTHOR']='Your Name'\nfilter['@package']='@package yourpackage'\nfilter['@license']='@license BSD'\nfilter['"'$'"COMPANY']='yourcompany'\nfilter['"'$'"EMAIL']='your@email.com'"
  [[ ! -f ~/.bashizzle ]] && printf "$tpl" > ~/.bashizzle
}
"$@"
